### ISSUE TITLE
notify when pledges expire

### ISSUE THREAD

**Issue by lucacioria** [buildo/pledge#3]
## stories
- as performer | requester, I want to be notified when a pledge expires so as to investigate what went wrong and fix the problem, or delete it if it was actually completed

## requirements
- send 1 notification to both performer and requester to notify that a pledge just expired
  - be within a few minutes of expiry date, super precision is not necessary
  - never send the same notification twice ;-)
- **manage migration of DB for new column**

## specs
- add a column `expiredNotificationSent` in the `pledges` table, default to false
- every 1 minute (`setInterval`), search for pledges where `expiredNotificationSent` is false and `deadline` is in the past
- notify and set `expiredNotificationSent` to true

## misc

{optional: other useful info}

**Comment by FrancescoCioria** [comment]
@lucacioria I would use slack reminders and add a column `slackReminderId` which we could use to invalidate a reminder if the pledge is deleted before its expiration datetime

**Comment by lucacioria** [comment]
Reading the docs, I understood that the reminders API requires us to be a Slack Application. Currently we're based on webhooks, we're not even a bot. That is why I chose, for simplicity, to go with this route.

I would definitely consider that option if/when we migrate this to be a real Slack Application.
